version: '3'
services:
  db:
    container_name: db 
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dumbflix
    ports:
      - 3306:3306
    volumes:
      - "/home/rizky/mysql:/var/lib/mysql"
  fe:
    container_name: backend
    image: dewabt8/backend
    ports:
      - 5000:5000
  

